### ISSUE TITLE
npm install on Windows

### ISSUE THREAD

**Issue by theaob** [DigitalArsenal/c137.js#1]
Hello, 
While trying to install on Windows, I'm getting the following error:
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c mkdir -p dist
npm ERR! A subdirectory or file dist already exists.
npm ERR! Error occurred while processing: dist.

Node version is v16.13.1
npm version is v8.3.0

**Comment by theaob** [comment]
Removing -p parameter from post install seemed to fix the issue (tried locally). I'm not posting a pull request because I don't know about the effect on Unix systems.

**Comment by TJKoury** [comment]
`mkdir -p` on Unix / Linux distros makes the directory if it doesn't exist already.  I might change the post install script to run the command in Node to get around cross-platform issues.

**Comment by cmcleese** [comment]
I agree that would help with script runners on systems which aren't unix

**Comment by TJKoury** [comment]
[This commit should fix it.](https://github.com/DigitalArsenal/c137.js/commit/2c0d4fb13afa1a77874a2b93e7921e961fd13a64)

**Comment by cmcleese** [comment]
great thanks! are you planning to add this to main for use via npm?

**Comment by TJKoury** [comment]
It has been added.

**Comment by Lost708** [comment]
@TJKoury - I am trying to run npm install on Windows and I'm getting the following error: 

npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node --max-old-space-size=4096 --experimental-json-modules --no-warnings --loader ts-node/esm ./scripts/postinstall.ts
npm ERR! C:\project\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:383
npm ERR!     throw new ERR_MODULE_NOT_FOUND(
npm ERR!           ^
npm ERR! CustomError: Cannot find module 'C:\project\node_modules\c137.js\scripts\postinstall.ts' imported from C:\project\node_modules\c137.js\
npm ERR!     at finalizeResolution (C:\project\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:383:11)

**Comment by TJKoury** [comment]
I think this might be due to `ts-node` module resolution not working correctly on Windows.  I’ll remove this as a post-install step.

**Comment by tomgelu** [comment]
still have the issue on wsl2: 

npm ERR! code 1
npm ERR! path /home/tgelu/cesium/front/node_modules/c137.js
npm ERR! command failed
npm ERR! command sh -c node --max-old-space-size=4096 --experimental-json-modules --no-warnings --loader ts-node/esm ./scripts/postinstall.ts
npm ERR! /home/tgelu/cesium/front/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:383
npm ERR!     throw new ERR_MODULE_NOT_FOUND(
npm ERR!           ^
npm ERR! CustomError: Cannot find module '/home/tgelu/cesium/front/node_modules/c137.js/scripts/postinstall.ts' imported from /home/tgelu/cesium/front/node_modules/c137.js/
npm ERR!     at finalizeResolution (/home/tgelu/cesium/front/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:383:11)
npm ERR!     at moduleResolve (/home/tgelu/cesium/front/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:818:10)
npm ERR!     at Object.defaultResolve (/home/tgelu/cesium/front/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:929:11)
npm ERR!     at /home/tgelu/cesium/front/node_modules/ts-node/src/esm.ts:228:33
npm ERR!     at entrypointFallback (/home/tgelu/cesium/front/node_modules/ts-node/src/esm.ts:179:34)
npm ERR!     at resolve (/home/tgelu/cesium/front/node_modules/ts-node/src/esm.ts:227:12)
npm ERR!     at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
npm ERR!     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
npm ERR!     at ESMLoader.import (node:internal/modules/esm/loader:276:22)
npm ERR!     at node:internal/modules/run_main:51:28
