### ISSUE TITLE
Add basic example

### ISSUE THREAD

**Issue by ashley-mort** [DigitalArsenal/c137.js#2]
Can you add a basic 'hello world' example for this?  Is there any way to include it straight in the browser (with a <script> tag) or do I need to use Node.js?

**Comment by TJKoury** [comment]
It will work in a browser, the same as any other es6 module.

**Comment by ashley-mort** [comment]
Here were my stumbling blocks:

1) I use NGINX as my app server and needed to add this to my nginx.conf:
http {
    include       mime.types;
    default_type  application/octet-stream;
	
    **types 
    {
        application/javascript mjs;
    }**
...

2) Alter my index.html to be:
`<html>
  <head>
    <title>Cesium</title>
  </head>
  <body>
    <div id="cesiumContainer"></div>
    <script type="module">

      import {
        createWorldTerrain,
        Ion,
        Viewer
      } from "./node_modules/c137.js/dist/c137.mjs";
	  
	  //Needed this for layer picker (Bing, etc) to work
	  Ion.defaultAccessToken = "MY_TOKEN";
	  
	  //Needed this or I get a fatal error at startup.
	  window.CESIUM_BASE_URL = window.location.href;
      
	  let viewer = new Viewer("cesiumContainer", {
		terrainProvider: createWorldTerrain(),
          });
    </script>
  </body>
</html>`
